import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,CalendarDays,Camera} from 'lucide-react';
import {day,daily,scores,type Entry,type Plan} from './data';
export default function Calendar({entries,plans,selected,onSelect,photoDates=[]}:{entries:Entry[];plans:Plan[];selected:string;onSelect:(date:string)=>void;photoDates?:string[]}) {
 const [month,setMonth]=useState(selected.slice(0,7));
 useEffect(()=>setMonth(selected.slice(0,7)),[selected]);
 const [y,m]=month.split('-').map(Number),start=new Date(Date.UTC(y,m-1,1)),pad=(start.getUTCDay()+6)%7,count=new Date(Date.UTC(y,m,0)).getUTCDate();
 const change=(delta:number)=>{const d=new Date(Date.UTC(y,m-1+delta,1));setMonth(d.toISOString().slice(0,7))};
 const rows=daily(entries),row=rows.find(r=>r.date===selected),score=scores(row),n=entries.filter(e=>e.date===selected).length;
 return <section className="card history-calendar" aria-label="記録カレンダー"><div className="calendar-toolbar"><div><h2><CalendarDays size={20}/> 記録カレンダー</h2></div><button className="textbtn" onClick={()=>{onSelect(day());setMonth(day().slice(0,7))}}>今日に戻る</button></div><div className="calendar-month"><button aria-label="前の月" onClick={()=>change(-1)}><ChevronLeft size={18}/></button><label><span className="sr-only">表示する月</span><input type="month" aria-label="表示する月" value={month} max={day().slice(0,7)} onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)&&e.target.value<=day().slice(0,7))setMonth(e.target.value)}}/></label><button aria-label="次の月" disabled={month>=day().slice(0,7)} onClick={()=>change(1)}><ChevronRight size={18}/></button></div><div className="calendar-week" aria-hidden="true">{['月','火','水','木','金','土','日'].map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{Array.from({length:pad},(_,i)=><span key={'pad'+i}/>)}{Array.from({length:count},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,recorded=entries.filter(e=>e.date===date).length,photo=photoDates.includes(date);return <button key={date} aria-label={`${date}、記録${recorded}件${photo?'、写真あり':''}`} aria-pressed={selected===date} disabled={date>day()} onClick={()=>onSelect(date)} className={`${selected===date?'selected ':''}${date===day()?'is-today ':''}${recorded?'has-records':''}`}><span>{i+1}</span><div className="calendar-marks">{recorded>0&&<i/>}{photo&&<Camera size={11}/>}</div></button>})}</div><div className="calendar-legend"><span>● 記録あり</span><span><Camera size={12}/> 写真あり</span></div><div className="day-summary"><div><span>{selected.replaceAll('-',' / ')}</span><h3>{n?`${n}件の暮らしの記録`:'この日は、まだまっさら。'}</h3></div><div><small>コンディション</small><strong>{score.total??'—'}<small> / 100</small></strong></div></div>{row&&<div className="day-chips">{row.sleep!==undefined&&<span>睡眠 <b>{row.sleep}</b>時間</span>}{row.steps!==undefined&&<span>歩数 <b>{row.steps.toLocaleString()}</b>歩</span>}{row.mood!==undefined&&<span>気分 <b>{row.mood}</b>/5</span>}{row.weight!==undefined&&<span>体重 <b>{row.weight}</b>kg</span>}</div>}{plans.filter(p=>p.date===selected).map(p=><div className="calendar-plan" key={p.id}><span>{p.done?'✓':'○'} {p.time??''}</span> {p.title}</div>)}</section>
}
