import {useState,useEffect,useRef,type FormEvent} from 'react';
import {Camera,Upload,X,Trash2,Check} from 'lucide-react';
import {preparePhoto,type Photo} from './photos';
import {day,type State} from './data';
async function api<T>(path:string,method='GET',data?:unknown):Promise<T>{const r=await fetch('/api/'+path,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const value=await r.json() as {error?:string};if(!r.ok)throw Error(value.error??'通信できませんでした。');return value as T}
export function PhotoAnalysis({photo}:{photo:Photo}){const a=photo.analysis;return <div className="photo-analysis"><span className="tag">{a.isFood?'食事の推定':'食事として認識できませんでした'}</span>{a.foods.length>0&&<h3>{a.foods.join('・')}</h3>}{a.caloriesMin!==null&&a.caloriesMax!==null&&<p className="photo-calories">推定 <strong>{a.caloriesMin}〜{a.caloriesMax}</strong> kcal</p>}{a.observations.length>0&&<><h4>写真からわかること</h4><ul>{a.observations.map(t=><li key={t}>{t}</li>)}</ul></>}{a.suggestions.length>0&&<><h4>食事のヒント</h4><ul>{a.suggestions.map(t=><li key={t}>{t}</li>)}</ul></>}<p className="photo-caution">{a.uncertainty}</p><small>写真だけでは健康状態や栄養の過不足、アレルギーは判断できません。</small></div>}
export default function PhotoPanel({state,demo,date,open,onClose,showList,onSaved,onDates,onSettings}:{state:State;demo:boolean;date:string;open:boolean;onClose:()=>void;showList:boolean;onSaved:()=>Promise<void>;onDates:(dates:string[])=>void;onSettings:()=>void}){
 const [uploadId,setUploadId]=useState(''),[photos,setPhotos]=useState<Photo[]>([]),[image,setImage]=useState(''),[selected,setSelected]=useState<Photo|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false),[entryDate,setEntryDate]=useState(date),[entryTime,setEntryTime]=useState('12:00'),[isOpen,setIsOpen]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),file=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);
 async function load(){if(demo){setPhotos([]);onDates([]);return}const rows=await api<Photo[]>('photos');setPhotos(rows);onDates(rows.map(p=>p.date));}
 useEffect(()=>{let live=true;if(demo){setPhotos([]);onDates([]);return}api<Photo[]>('photos').then(rows=>{if(live){setPhotos(rows);onDates(rows.map(p=>p.date))}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[demo,state.username,state.entries,state.settings.enabled.glasses]);
 useEffect(()=>{if(open){setSelected(null);setImage('');setConsent(false);setError('');setEntryDate(date);setEntryTime(new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'}).format(new Date()));setIsOpen(true)}},[open]);
 useEffect(()=>{if(isOpen)dialog.current?.showModal();else dialog.current?.close()},[isOpen]);
 const close=()=>{if(busy)return;setIsOpen(false);onClose()};
 async function work(task:()=>Promise<void>){setBusy(true);setError('');try{await task()}catch(e){setError(e instanceof Error?e.message:'処理できませんでした。')}finally{setBusy(false)}}
 async function choose(files:FileList|null){const item=files?.[0];if(!item)return;await work(async()=>{setImage(await preparePhoto(item));setUploadId(crypto.randomUUID());setSelected(null)});if(file.current)file.current.value='';if(camera.current)camera.current.value=''}
 async function analyze(){if(!image||!consent)return;await work(async()=>{const result=await api<Photo>('photos/analyze','POST',{image,date:entryDate,time:entryTime,source:'manual',externalId:uploadId});setSelected(result);await load()})}
 async function confirm(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);await work(async()=>{await api(`photos/${selected.id}/confirm`,'POST',{date:String(f.get('date')),time:String(f.get('time')),title:String(f.get('title')),note:String(f.get('note'))});await onSaved();await load();setIsOpen(false);onClose()})}
 async function remove(){if(!selected)return;await work(async()=>{await api('photos/'+selected.id,'DELETE');await load();await onSaved();setSelected(null);setImage('');setIsOpen(false);onClose()})}
 const current=photos.filter(p=>p.date===date);
 return <>{showList&&current.length>0&&<section className="photo-list"><div className="sectionhead"><h2>写真</h2><span>{current.length}枚</span></div><div className="photo-grid">{current.map(p=><button className="photo-card" key={p.id} onClick={()=>{setSelected(p);setImage('');setError('');setIsOpen(true)}}><img loading="lazy" src={p.imageUrl} alt={p.analysis.foods.join('、')||'アップロードした写真'}/><div><span>{p.time} · {p.status==='pending'?'確認待ち':'記録済み'}</span><strong>{p.analysis.foods.join('・')||'写真の記録'}</strong>{p.source==='glasses'&&<small>スマートグラスから受信</small>}</div></button>)}</div></section>}
 {showList&&error&&!isOpen&&<p role="alert" className="error">{error}</p>}
 <dialog ref={dialog} className="photo-dialog" aria-label="写真を追加・分析" onCancel={e=>{if(busy)e.preventDefault();else close()}}><div className="modalhead"><h2>{selected?'写真の分析結果':'写真を追加'}</h2><button disabled={busy} aria-label="写真の画面を閉じる" onClick={close}><X size={20}/></button></div>{error&&<p role="alert" className="error">{error}</p>}
 {demo?<><p>写真分析はアカウントを作成して利用できます。体験モードでは写真を送信・保存しません。</p><button onClick={close}>閉じる</button></>:selected?<><img className="photo-preview" src={selected.imageUrl} alt="分析した写真"/><PhotoAnalysis photo={selected}/>{selected.status==='pending'?<form onSubmit={confirm}><h3>内容を確認して記録</h3><p>料理名やメモを修正できます。推定値は参考情報として残ります。</p><div className="formgrid"><label>日付<input name="date" type="date" required max={day()} defaultValue={selected.date}/></label><label>時刻<input name="time" type="time" required defaultValue={selected.time}/></label></div><label>料理名・タイトル<input name="title" required maxLength={200} defaultValue={selected.analysis.foods.join('・').slice(0,200)||'写真の記録'}/></label><label>量や材料の補足<textarea name="note" maxLength={2000} placeholder="例：ご飯は半分、ドレッシングは別添え"/></label><button className="primary" disabled={busy}><Check size={17}/>{busy?'保存中…':'この内容で記録'}</button></form>:<p className="hint">{selected.date}のライフログに保存されています。日付や内容はライフログから編集できます。</p>}<button className="textbtn danger" disabled={busy} onClick={remove}><Trash2 size={16}/> 写真を削除{selected.status==='confirmed'?'（記録は残す）':''}</button></>:<><p>食事の写真から、料理や栄養の傾向を推定します。</p><input ref={file} className="sr-only" aria-label="食事の写真ファイル" type="file" accept="image/*" onChange={e=>choose(e.target.files)}/><input ref={camera} className="sr-only" aria-label="カメラで撮影" type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files)}/><div className="photo-upload-actions"><button disabled={busy} onClick={()=>file.current?.click()}><Upload size={18}/> 写真を選ぶ</button><button disabled={busy} onClick={()=>camera.current?.click()}><Camera size={18}/> 撮影する</button></div>{image&&<img className="photo-preview" src={image} alt="送信前の写真プレビュー"/>}<div className="formgrid"><label>日付<input type="date" max={day()} required value={entryDate} onChange={e=>setEntryDate(e.target.value)}/></label><label>時刻<input type="time" required value={entryTime} onChange={e=>setEntryTime(e.target.value)}/></label></div><small>送信前に写真を縮小し、位置情報などの付加情報を除去します。保存されるのは縮小画像です。</small>{!state.settings.aiConsent?<div className="hint"><p>写真を分析するには、設定でAI分析を有効にしてください。</p><button onClick={()=>{close();onSettings()}}>設定を開く</button></div>:<><label className="photo-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>この写真をCloudflare Workers AIで分析し、縮小画像と結果を保存する</span></label><button className="primary" disabled={busy||!image||!consent||!entryDate||!entryTime||!state.settings.manual} onClick={analyze}>{busy?'写真を分析しています…':'写真を分析する'}</button></>}</>}
 </dialog></>;
}
